import { sql } from 'drizzle-orm';

import { unwrapTxScope } from '../../../platform/db/tx-scope.js';
import type { TxScope } from '../../../shared/ports/unit-of-work.js';
import type { CompanyId, UserId } from '../../../shared/types/ids.js';

/**
 * Identity persistence (ER-005, ER-008).
 *
 * The only place in this module that touches the database. Every method takes
 * a `TxScope` and can obtain a connection no other way, so nothing here can
 * run outside a tenant-bound transaction.
 *
 * Every value is a bind parameter. Nothing is interpolated into SQL, ever
 * (ER-031, SEC-042) — not even a column name, not even in an ORDER BY.
 */

export interface CompanyRow extends Record<string, unknown> {
  readonly id: string;
  readonly slug: string;
  readonly status: string;
}

export interface AuthUserRow extends Record<string, unknown> {
  readonly id: string;
  readonly companyId: string;
  readonly email: string;
  readonly fullName: string;
  readonly passwordHash: string | null;
  readonly status: string;
  readonly emailVerifiedAt: Date | null;
  readonly mfaEnabled: boolean;
  readonly failedLoginCount: number;
  /**
   * `Date | string` because it depends on how it was read: the driver returns
   * a Date from a plain SELECT and a string from the set-returning
   * `auth_lookup_user_by_email`. Typed as both so callers are forced to
   * coerce, rather than being told it is a Date and finding out otherwise.
   */
  readonly lockedUntil: Date | string | null;
}

export interface InsertCompanyInput {
  readonly id: string;
  readonly name: string;
  readonly slug: string;
  readonly countryCode: string;
}

export interface InsertUserInput {
  readonly companyId: CompanyId;
  readonly email: string;
  readonly fullName: string;
  readonly passwordHash: string;
}

export interface InsertSessionInput {
  readonly userId: UserId;
  readonly companyId: CompanyId;
  readonly familyId: string;
  readonly refreshTokenHash: string;
  readonly expiresAt: Date;
  readonly ipAddress: string | null;
  readonly deviceInfo: string | null;
}

export class IdentityRepository {
  /**
   * Mints a company id before the company exists.
   *
   * Needed because `companies` is RLS-checked on its own primary key: the
   * WITH CHECK is `id = current_setting('app.current_company_id')`, so the
   * tenant context must already hold the id at INSERT time. Binding after the
   * insert — the order 08 §3 describes — cannot work against that policy.
   *
   * Generated by PostgreSQL rather than in Node so it stays `uuidv7()`, and so
   * the ordering property the schema relies on is not quietly traded for a v4
   * from `crypto.randomUUID()`.
   */
  async nextCompanyId(tx: TxScope): Promise<string> {
    const result = await unwrapTxScope(tx).execute<{ id: string }>(sql`select uuidv7() as id`);
    const row = result.rows[0];
    if (row === undefined) throw new Error('uuidv7() returned no row');
    return row.id;
  }

  /**
   * Reserves the slug by inserting the company.
   *
   * Availability is NOT checked with a prior SELECT. Two simultaneous signups
   * would both see the slug free and both proceed; the unique index is the
   * only thing that actually decides, so the insert is the check. The caller
   * translates the constraint violation into the generic 422 (08 §3).
   *
   * `owner_user_id` stays NULL here — the user does not exist yet. Closing
   * that loop is `setOwner`, in this same transaction.
   */
  async insertCompany(tx: TxScope, input: InsertCompanyInput): Promise<CompanyRow> {
    const result = await unwrapTxScope(tx).execute<CompanyRow>(sql`
      insert into companies (id, name, slug, company_type, status, country_code)
      values (${input.id}, ${input.name}, ${input.slug}, 1, 'pending_verification', ${input.countryCode})
      returning id, slug, status
    `);

    const row = result.rows[0];
    if (row === undefined) throw new Error('company insert returned no row');
    return row;
  }

  async insertUser(tx: TxScope, input: InsertUserInput): Promise<{ id: string }> {
    const result = await unwrapTxScope(tx).execute<{ id: string }>(sql`
      insert into users (company_id, email, password_hash, full_name, status)
      values (${input.companyId}, ${input.email}, ${input.passwordHash}, ${input.fullName}, 'pending')
      returning id
    `);

    const row = result.rows[0];
    if (row === undefined) throw new Error('user insert returned no row');
    return row;
  }

  /** The second half of the circular FK (06 §3). Same transaction, always. */
  async setOwner(tx: TxScope, companyId: CompanyId, userId: UserId): Promise<void> {
    await unwrapTxScope(tx).execute(sql`
      update companies set owner_user_id = ${userId}, updated_at = now()
      where id = ${companyId}
    `);
  }

  /**
   * Assigns a platform-default role by key.
   *
   * The role row itself is shared — `company_id IS NULL`, seeded by migration
   * 015 — while the assignment is tenant-scoped. Returns the number of rows so
   * the caller can fail loudly when the catalog was never seeded, rather than
   * creating an owner with no permissions at all.
   */
  async assignPlatformRole(
    tx: TxScope,
    companyId: CompanyId,
    userId: UserId,
    roleKey: string,
  ): Promise<number> {
    const result = await unwrapTxScope(tx).execute(sql`
      insert into user_roles (company_id, user_id, role_id, granted_by)
      select ${companyId}, ${userId}, r.id, ${userId}
        from roles r
       where r.key = ${roleKey} and r.company_id is null
    `);

    return result.rowCount ?? 0;
  }

  /**
   * Looks a user up for authentication, before any tenant is known.
   *
   * Goes through `auth_lookup_user_by_email`, a SECURITY DEFINER function
   * created in migration 016. It has to: login runs under `withoutTenant`, and
   * `users` is under FORCE ROW LEVEL SECURITY whose policy matches nothing
   * when the GUC is unset — so a plain SELECT here returns zero rows and login
   * can never succeed for anyone.
   *
   * The function is the narrow alternative to widening the policy. It returns
   * only the columns authentication needs, excludes platform staff, and is the
   * single pre-tenant read path in the system. Email is globally unique
   * (D-049), so there is exactly one candidate row and no ambiguity to resolve.
   */
  async findAuthUserByEmail(tx: TxScope, email: string): Promise<AuthUserRow | undefined> {
    const result = await unwrapTxScope(tx).execute<AuthUserRow>(sql`
      select id,
             company_id         as "companyId",
             email,
             password_hash      as "passwordHash",
             status,
             email_verified_at  as "emailVerifiedAt",
             mfa_enabled        as "mfaEnabled",
             failed_login_count as "failedLoginCount",
             locked_until       as "lockedUntil"
        from auth_lookup_user_by_email(${email}::citext)
    `);

    return result.rows[0];
  }

  /** The user's display name, read once tenant context is bound. */
  async findFullName(tx: TxScope, userId: UserId): Promise<string> {
    const result = await unwrapTxScope(tx).execute<{ fullName: string }>(sql`
      select full_name as "fullName" from users where id = ${userId}
    `);
    return result.rows[0]?.fullName ?? '';
  }

  /**
   * Records a failed attempt and locks on threshold, in one statement.
   *
   * One statement rather than read-then-write: two concurrent wrong guesses
   * would both read the same count and both write count+1, so the threshold
   * would take twice as many attempts to reach as configured.
   */
  async recordFailedLogin(
    tx: TxScope,
    userId: string,
    threshold: number,
    lockMinutes: number,
  ): Promise<void> {
    /* Also a SECURITY DEFINER function, for the same reason as the lookup: it
       runs before a tenant is bound, so an ordinary UPDATE would match no rows
       and the lockout counter would never move. */
    await unwrapTxScope(tx).execute(
      sql`select auth_record_failed_login(${userId}::uuid, ${threshold}, ${lockMinutes})`,
    );
  }

  async recordSuccessfulLogin(tx: TxScope, userId: string): Promise<void> {
    await unwrapTxScope(tx).execute(sql`select auth_record_successful_login(${userId}::uuid)`);
  }

  async insertSession(tx: TxScope, input: InsertSessionInput): Promise<{ id: string }> {
    const result = await unwrapTxScope(tx).execute<{ id: string }>(sql`
      insert into sessions (user_id, company_id, family_id, refresh_token_hash,
                            expires_at, ip_address, device_info)
      values (${input.userId}, ${input.companyId}, ${input.familyId}, ${input.refreshTokenHash},
              ${input.expiresAt}, ${input.ipAddress}::inet, ${input.deviceInfo})
      returning id
    `);

    const row = result.rows[0];
    if (row === undefined) throw new Error('session insert returned no row');
    return row;
  }

  /**
   * Stores the email-verification token, hashed (ER-047).
   *
   * Kept in `settings` rather than a dedicated table only because the
   * verification-token table lands with T-026's group; this row is scoped to
   * the tenant and replaced on resend.
   */
  async storeVerificationToken(
    tx: TxScope,
    companyId: CompanyId,
    userId: UserId,
    tokenHash: string,
    expiresAt: Date,
  ): Promise<void> {
    await unwrapTxScope(tx).execute(sql`
      insert into settings (company_id, key, value)
      values (
        ${companyId},
        ${'auth.email_verification.' + userId},
        ${JSON.stringify({ tokenHash, expiresAt: expiresAt.toISOString() })}::jsonb
      )
      on conflict (company_id, key) where company_id is not null
      do update set value = excluded.value, updated_at = now()
    `);
  }

  async readVerificationToken(
    tx: TxScope,
    userId: UserId,
  ): Promise<{ tokenHash: string; expiresAt: string } | undefined> {
    const result = await unwrapTxScope(tx).execute<{
      value: { tokenHash: string; expiresAt: string };
    }>(sql`
      select value from settings where key = ${'auth.email_verification.' + userId}
    `);

    return result.rows[0]?.value;
  }

  /**
   * Marks a verified user active. The **company** stays
   * `pending_verification` — it becomes active at MFA enrolment (D-050),
   * because that is when the owner grant lands and the tenant gains anyone who
   * can administer it.
   */
  async activateVerifiedUser(tx: TxScope, userId: UserId): Promise<void> {
    await unwrapTxScope(tx).execute(sql`
      update users
         set status = 'active', email_verified_at = now()
       where id = ${userId} and email_verified_at is null
    `);
  }

  async findEmail(tx: TxScope, userId: UserId): Promise<string> {
    const result = await unwrapTxScope(tx).execute<{ email: string }>(sql`
      select email from users where id = ${userId}
    `);
    return result.rows[0]?.email ?? '';
  }

  /** Stores the encrypted TOTP seed without enabling MFA yet. */
  async storeMfaSecret(tx: TxScope, userId: UserId, secretEncrypted: string): Promise<void> {
    await unwrapTxScope(tx).execute(sql`
      update users set mfa_secret_encrypted = ${secretEncrypted} where id = ${userId}
    `);
  }

  async readMfaSecret(
    tx: TxScope,
    userId: UserId,
  ): Promise<{ secret: string; email: string } | undefined> {
    const result = await unwrapTxScope(tx).execute<{ secret: string | null; email: string }>(sql`
      select mfa_secret_encrypted as secret, email from users where id = ${userId}
    `);
    const row = result.rows[0];
    if (row?.secret === null || row?.secret === undefined) return undefined;
    return { secret: row.secret, email: row.email };
  }

  /**
   * Flips the flag. A separate statement from the grant, and it must run
   * first: `trg_owner_requires_mfa` reads `users.mfa_enabled` when the
   * `user_roles` row is inserted, so this ordering is what makes the founding
   * grant legal rather than an exemption (D-050).
   */
  async enableMfa(tx: TxScope, userId: UserId): Promise<void> {
    await unwrapTxScope(tx).execute(sql`
      update users set mfa_enabled = true where id = ${userId}
    `);
  }

  /** Activates the company once it has an MFA-enrolled owner (D-050). */
  async activateCompany(tx: TxScope, companyId: CompanyId): Promise<void> {
    await unwrapTxScope(tx).execute(sql`
      update companies set status = 'active'
       where id = ${companyId} and status = 'pending_verification'
    `);
  }
}
