import { sql } from 'drizzle-orm';

import { unwrapTxScope } from '../../../platform/db/tx-scope.js';
import type { TxScope } from '../../../shared/ports/unit-of-work.js';
import type { CompanyId, UserId } from '../../../shared/types/ids.js';

/**
 * Identity persistence (ER-005, ER-008).
 *
 * The only place in this module that touches the database. Every method takes
 * a `TxScope` and can obtain a connection no other way, so nothing here can
 * run outside a tenant-bound transaction.
 *
 * Every value is a bind parameter. Nothing is interpolated into SQL, ever
 * (ER-031, SEC-042) — not even a column name, not even in an ORDER BY.
 */

export interface CompanyRow extends Record<string, unknown> {
  readonly id: string;
  readonly slug: string;
  readonly status: string;
}

export interface AuthUserRow extends Record<string, unknown> {
  readonly id: string;
  readonly companyId: string;
  readonly email: string;
  readonly fullName: string;
  readonly passwordHash: string | null;
  readonly status: string;
  readonly emailVerifiedAt: Date | null;
  readonly mfaEnabled: boolean;
  readonly failedLoginCount: number;
  readonly lockedUntil: Date | null;
}

export interface InsertCompanyInput {
  readonly id: string;
  readonly name: string;
  readonly slug: string;
  readonly countryCode: string;
}

export interface InsertUserInput {
  readonly companyId: CompanyId;
  readonly email: string;
  readonly fullName: string;
  readonly passwordHash: string;
}

export interface InsertSessionInput {
  readonly userId: UserId;
  readonly companyId: CompanyId;
  readonly familyId: string;
  readonly refreshTokenHash: string;
  readonly expiresAt: Date;
  readonly ipAddress: string | null;
  readonly deviceInfo: string | null;
}

export class IdentityRepository {
  /**
   * Mints a company id before the company exists.
   *
   * Needed because `companies` is RLS-checked on its own primary key: the
   * WITH CHECK is `id = current_setting('app.current_company_id')`, so the
   * tenant context must already hold the id at INSERT time. Binding after the
   * insert — the order 08 §3 describes — cannot work against that policy.
   *
   * Generated by PostgreSQL rather than in Node so it stays `uuidv7()`, and so
   * the ordering property the schema relies on is not quietly traded for a v4
   * from `crypto.randomUUID()`.
   */
  async nextCompanyId(tx: TxScope): Promise<string> {
    const result = await unwrapTxScope(tx).execute<{ id: string }>(sql`select uuidv7() as id`);
    const row = result.rows[0];
    if (row === undefined) throw new Error('uuidv7() returned no row');
    return row.id;
  }

  /**
   * Reserves the slug by inserting the company.
   *
   * Availability is NOT checked with a prior SELECT. Two simultaneous signups
   * would both see the slug free and both proceed; the unique index is the
   * only thing that actually decides, so the insert is the check. The caller
   * translates the constraint violation into the generic 422 (08 §3).
   *
   * `owner_user_id` stays NULL here — the user does not exist yet. Closing
   * that loop is `setOwner`, in this same transaction.
   */
  async insertCompany(tx: TxScope, input: InsertCompanyInput): Promise<CompanyRow> {
    const result = await unwrapTxScope(tx).execute<CompanyRow>(sql`
      insert into companies (id, name, slug, company_type, status, country_code)
      values (${input.id}, ${input.name}, ${input.slug}, 1, 'pending_verification', ${input.countryCode})
      returning id, slug, status
    `);

    const row = result.rows[0];
    if (row === undefined) throw new Error('company insert returned no row');
    return row;
  }

  async insertUser(tx: TxScope, input: InsertUserInput): Promise<{ id: string }> {
    const result = await unwrapTxScope(tx).execute<{ id: string }>(sql`
      insert into users (company_id, email, password_hash, full_name, status)
      values (${input.companyId}, ${input.email}, ${input.passwordHash}, ${input.fullName}, 'pending')
      returning id
    `);

    const row = result.rows[0];
    if (row === undefined) throw new Error('user insert returned no row');
    return row;
  }

  /** The second half of the circular FK (06 §3). Same transaction, always. */
  async setOwner(tx: TxScope, companyId: CompanyId, userId: UserId): Promise<void> {
    await unwrapTxScope(tx).execute(sql`
      update companies set owner_user_id = ${userId}, updated_at = now()
      where id = ${companyId}
    `);
  }

  /**
   * Assigns a platform-default role by key.
   *
   * The role row itself is shared — `company_id IS NULL`, seeded by migration
   * 015 — while the assignment is tenant-scoped. Returns the number of rows so
   * the caller can fail loudly when the catalog was never seeded, rather than
   * creating an owner with no permissions at all.
   */
  async assignPlatformRole(
    tx: TxScope,
    companyId: CompanyId,
    userId: UserId,
    roleKey: string,
  ): Promise<number> {
    const result = await unwrapTxScope(tx).execute(sql`
      insert into user_roles (company_id, user_id, role_id, granted_by)
      select ${companyId}, ${userId}, r.id, ${userId}
        from roles r
       where r.key = ${roleKey} and r.company_id is null
    `);

    return result.rowCount ?? 0;
  }

  /**
   * Looks a user up for authentication.
   *
   * Deliberately **not** tenant-scoped: login happens before any tenant
   * context exists, so this runs under `withoutTenant`. Email is unique per
   * company, so a single address could in principle exist in two tenants —
   * `limit 1` with a deterministic order keeps the outcome stable rather than
   * depending on physical row order.
   *
   * Platform staff (`company_id is null`) are excluded: they authenticate on
   * the separate platform surface (08 §2), and letting them through here would
   * put staff credentials on the tenant login endpoint.
   */
  async findAuthUserByEmail(tx: TxScope, email: string): Promise<AuthUserRow | undefined> {
    const result = await unwrapTxScope(tx).execute<AuthUserRow>(sql`
      select id,
             company_id        as "companyId",
             email,
             full_name         as "fullName",
             password_hash     as "passwordHash",
             status,
             email_verified_at as "emailVerifiedAt",
             mfa_enabled       as "mfaEnabled",
             failed_login_count as "failedLoginCount",
             locked_until      as "lockedUntil"
        from users
       where email = ${email} and company_id is not null
       order by created_at
       limit 1
    `);

    return result.rows[0];
  }

  /**
   * Records a failed attempt and locks on threshold, in one statement.
   *
   * One statement rather than read-then-write: two concurrent wrong guesses
   * would both read the same count and both write count+1, so the threshold
   * would take twice as many attempts to reach as configured.
   */
  async recordFailedLogin(
    tx: TxScope,
    userId: string,
    threshold: number,
    lockMinutes: number,
  ): Promise<void> {
    await unwrapTxScope(tx).execute(sql`
      update users
         set failed_login_count = failed_login_count + 1,
             locked_until = case
               when failed_login_count + 1 >= ${threshold}
               then now() + make_interval(mins => ${lockMinutes})
               else locked_until
             end,
             updated_at = now()
       where id = ${userId}
    `);
  }

  async recordSuccessfulLogin(tx: TxScope, userId: string): Promise<void> {
    await unwrapTxScope(tx).execute(sql`
      update users
         set failed_login_count = 0, locked_until = null,
             last_login_at = now(), updated_at = now()
       where id = ${userId}
    `);
  }

  async insertSession(tx: TxScope, input: InsertSessionInput): Promise<{ id: string }> {
    const result = await unwrapTxScope(tx).execute<{ id: string }>(sql`
      insert into sessions (user_id, company_id, family_id, refresh_token_hash,
                            expires_at, ip_address, device_info)
      values (${input.userId}, ${input.companyId}, ${input.familyId}, ${input.refreshTokenHash},
              ${input.expiresAt}, ${input.ipAddress}::inet, ${input.deviceInfo})
      returning id
    `);

    const row = result.rows[0];
    if (row === undefined) throw new Error('session insert returned no row');
    return row;
  }

  /**
   * Stores the email-verification token, hashed (ER-047).
   *
   * Kept in `settings` rather than a dedicated table only because the
   * verification-token table lands with T-026's group; this row is scoped to
   * the tenant and replaced on resend.
   */
  async storeVerificationToken(
    tx: TxScope,
    companyId: CompanyId,
    userId: UserId,
    tokenHash: string,
    expiresAt: Date,
  ): Promise<void> {
    await unwrapTxScope(tx).execute(sql`
      insert into settings (company_id, key, value)
      values (
        ${companyId},
        ${'auth.email_verification.' + userId},
        ${JSON.stringify({ tokenHash, expiresAt: expiresAt.toISOString() })}::jsonb
      )
      on conflict (company_id, key) where company_id is not null
      do update set value = excluded.value, updated_at = now()
    `);
  }

  async readVerificationToken(
    tx: TxScope,
    userId: UserId,
  ): Promise<{ tokenHash: string; expiresAt: string } | undefined> {
    const result = await unwrapTxScope(tx).execute<{
      value: { tokenHash: string; expiresAt: string };
    }>(sql`
      select value from settings where key = ${'auth.email_verification.' + userId}
    `);

    return result.rows[0]?.value;
  }

  /**
   * Activates a verified user and their company in one statement each.
   *
   * The company moves out of `pending_verification` at the same time: a
   * verified owner with a company still pending is a state nothing else in the
   * system knows how to interpret.
   */
  async activateVerifiedUser(tx: TxScope, companyId: CompanyId, userId: UserId): Promise<void> {
    const client = unwrapTxScope(tx);
    await client.execute(sql`
      update users
         set status = 'active', email_verified_at = now(), updated_at = now()
       where id = ${userId} and email_verified_at is null
    `);
    await client.execute(sql`
      update companies
         set status = 'active', updated_at = now()
       where id = ${companyId} and status = 'pending_verification'
    `);
  }
}
