import { generateKeyPairSync, randomBytes } from 'node:crypto';
import { resolve } from 'node:path';

import {
  DEV_DATABASE,
  MIGRATOR_ROLE,
  TEST_DATABASE,
  TEST_RUNNER_ROLE,
  type RoleName,
} from './roles.js';

/**
 * What a generated `.env` contains, and the secrets that go into it.
 *
 * Every secret is generated locally and is unique to this install (SEC-073).
 * None is printed; `.env` is written mode 600 and gitignored (ER-046).
 */

const REPO_ROOT = resolve(import.meta.dirname, '..', '..');

export function generateSecret(bytes: number): string {
  // base64url: [A-Za-z0-9_-] only, so it needs no escaping inside a URL.
  return randomBytes(bytes).toString('base64url');
}

function generateJwtKeypairBase64(): { privateKey: string; publicKey: string } {
  const { privateKey, publicKey } = generateKeyPairSync('ed25519', {
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
    publicKeyEncoding: { type: 'spki', format: 'pem' },
  });
  return {
    privateKey: Buffer.from(privateKey).toString('base64'),
    publicKey: Buffer.from(publicKey).toString('base64'),
  };
}

function buildUrl(role: RoleName, password: string, database: string): string {
  const host = process.env['PGHOST'] ?? 'localhost';
  const port = process.env['PGPORT'] ?? '5432';
  return `postgres://${role}:${password}@${host}:${port}/${database}`;
}

/**
 * The three test connections (D-046, D-048a). No one role may hold all three
 * capabilities the harness needs, so there are three URLs rather than one.
 */
function testConnections(passwords: ReadonlyMap<RoleName, string>): string {
  const app = buildUrl('findneo_app', passwords.get('findneo_app') ?? '', TEST_DATABASE);
  const owner = buildUrl(MIGRATOR_ROLE, passwords.get(MIGRATOR_ROLE) ?? '', TEST_DATABASE);
  const runner = buildUrl(TEST_RUNNER_ROLE, passwords.get(TEST_RUNNER_ROLE) ?? '', 'postgres');
  return `# Tests run against native PostgreSQL (D-046); there is no container runtime on
# this machine. Three connections, because no one role may hold all three
# capabilities the harness needs:
#   app      owns nothing, so FORCE ROW LEVEL SECURITY genuinely applies to it
#   owner    migrates, seeds fixtures, and proves seeded rows exist
#   runner   holds CREATEDB, and is the only role that can clone the template
#            per test (D-048a). findneo_migrator is NOCREATEDB by design.
# Every database the harness creates or drops must end in "_test", checked
# before any DDL runs.
DATABASE_URL_TEST=${app}
DATABASE_URL_TEST_OWNER=${owner}
DATABASE_URL_TEST_RUNNER=${runner}`;
}

export function renderEnvFile(passwords: ReadonlyMap<RoleName, string>): string {
  const appPassword = passwords.get('findneo_app') ?? '';
  const migratorPassword = passwords.get(MIGRATOR_ROLE) ?? '';
  const keypair = generateJwtKeypairBase64();
  /* base64, not base64url: SecretBox decodes with Buffer.from(_, 'base64'),
     and 32 raw bytes must round-trip to exactly 32. */
  const secretEncryptionKey = randomBytes(32).toString('base64');
  const storageRoot = resolve(REPO_ROOT, 'var/storage').replaceAll('\\', '/');

  return `# Generated by \`pnpm db:setup\`. Never commit this file (ER-046).
# Every value below is validated at startup by src/platform/config (SEC-060).

NODE_ENV=development
LOG_LEVEL=debug

API_HOST=127.0.0.1
API_PORT=3000

# /health/* and /metrics run on their own listener, loopback only (SEC-021).
OPS_HOST=127.0.0.1
OPS_PORT=9464

DATABASE_URL=${buildUrl('findneo_app', appPassword, DEV_DATABASE)}
DATABASE_POOL_MAX=10

${testConnections(passwords)}

# Migration tooling only. The application config loader deliberately does NOT
# read this — the API and worker must never hold table-owner credentials.
DATABASE_URL_MIGRATOR=${buildUrl(MIGRATOR_ROLE, migratorPassword, DEV_DATABASE)}

STORAGE_DRIVER=filesystem
STORAGE_FS_ROOT=${storageRoot}

MAIL_DRIVER=log

# Base64-encoded PEM. Generated locally, unique to this install (SEC-073).
JWT_PRIVATE_KEY=${keypair.privateKey}
JWT_PUBLIC_KEY=${keypair.publicKey}
COOKIE_SECRET=${generateSecret(32)}

SECRET_ENCRYPTION_KEY=${secretEncryptionKey}
WORKER_DOMAINS=all
SWAGGER_ENABLED=true
OTEL_ENABLED=false
`;
}
